Introduce MtsTaskFn to fix update_functions.py in Ghidra
update_functions.py and Ghidra have problems with those function
pointer declarations in mts_new.h header:

updating function: mts_boot_task_8008AAC4; parameter number: 1
Traceback (most recent call last):
  File "C:\mgs_reversing\build\ghidra_scripts\update_functions.py", line 127, in <module>
    updated_ghidra_params.append(ParameterImpl(param_name, data_type, currentProgram))
	at ghidra.program.model.listing.VariableUtilities.checkDataType(VariableUtilities.java:308)
	at ghidra.program.model.listing.VariableUtilities.checkDataType(VariableUtilities.java:340)
	at ghidra.program.model.listing.VariableImpl.<init>(VariableImpl.java:184)
	at ghidra.program.model.listing.ParameterImpl.<init>(ParameterImpl.java:264)
	at ghidra.program.model.listing.ParameterImpl.<init>(ParameterImpl.java:57)
	at jdk.internal.reflect.GeneratedConstructorAccessor142.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:213)
ghidra.util.exception.InvalidInputException: ghidra.util.exception.InvalidInputException: The void type is not permitted - allowed for function return use only

A quick fix applied in this commit is to introduce a new typedef: MtsTaskFn.